### ISSUE TITLE
Filename Case vs case vs CASE

### ISSUE THREAD

**Issue by qubodup** [adonaac/thranduil#17]
Hi,

on Linux `love .` doesn't work because `ui/input` is `ui/Input` (uppercase i).

To ensure that case-sensitive file systems work out of the box, please take care to use the case you intended.

<pre>Error: ui/UI.lua:5: module 'ui/input/Input' not found:
	no field package.preload['ui/input/Input']
	no file 'ui/input/Input.lua' in LOVE game directories.
	no file 'ui/input/Input/init.lua' in LOVE game directories.
	no file 'ui/input/Input.so' in LOVE paths.
	no file './ui/input/Input.lua'
	no file '/usr/share/luajit-2.0.4/ui/input/Input.lua'
	no file '/usr/local/share/lua/5.1/ui/input/Input.lua'
	no file '/usr/local/share/lua/5.1/ui/input/Input/init.lua'
	no file '/usr/share/lua/5.1/ui/input/Input.lua'
	no file '/usr/share/lua/5.1/ui/input/Input/init.lua'
	no file './ui/input/Input.so'
	no file '/usr/local/lib/lua/5.1/ui/input/Input.so'
	no file '/usr/lib/lua/5.1/ui/input/Input.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	ui/UI.lua:5: in main chunk
	[C]: in function 'require'
	main.lua:1: in main chunk
	[C]: in function 'require'
	[string "boot.lua"]:374: in function <[string "boot.lua"]:244></pre>

**Comment by S0lll0s** [comment]
also `require` should never be called with slashes (`/`) in the name, but always with dots instead. It is also convention to have all filenames lowercase and to only capitalize "Objects" (or whatever comes closest in your coding style)

    local ui_path = tostring(...):sub(1, -3)
    local UI = {}
    require(ui_path .. 'utf8-l')
    UI.Object = require(ui_path .. 'classic.classic')
    UI.Input = require(ui_path .. 'input.input')
    UI.Text = require(ui_path .. 'popo.text')
    UI.Math = require(ui_path .. 'mlib.mlib')

**Comment by Positive07** [comment]
Other note, if your library depends on multiple files it is recommended you use `init.lua` for the main file so you can simply require it with `ui` and also allows you to delete that ugly `tostring(...):sub(1, -3)` and turn it into `...`. This was recommended and totally ignored [here](https://github.com/adonaac/thranduil/pull/3) without a reason whatsoever

**Comment by adonaac** [comment]
I don't fully understand what the issue here is. Could someone explain it further? Does the library fail to load its files right now?

**Comment by VideahGams** [comment]
Linux uses a case-sensitive file system, whilst Windows doesn't.
This can cause hidden errors that only Linux users will get if you're not careful.

For example, the path to Input.lua is ```ui/Input/Input```

But in UI.lua it is required as ```ui/input/Input``` which causes an error.

As @Positive07 said, it is also recommended to use ```init.lua``` as the main file instead of ```UI.lua``` as it means requiring goes from this:
```lua
require 'ui.UI'
```

To this:
```lua
require 'ui'
```

Which is just nicer overall.

As @S0lll0s said, It is also recommended you use dots instead of slashes when requiring things.

I've created a pull request that fixes all of these things #19.

**Comment by adonaac** [comment]
Thanks VideahGams, I guess that should fix it.
