### ISSUE TITLE
[docs] assigning a default theme to everything

### ISSUE THREAD

**Issue by raingloom** [adonaac/thranduil#26]
This might sound like noobness, but
If there is a way to simply require a theme and add it to everything by default, without having to use an extension for everything created later on, please add it to the docs, so people don't have to research it.
If there isn't, there should be :3

**Comment by Positive07** [comment]
+1 to this! having to write {extensions = {Theme.Frame}} for each thing is kinda annoying

**Comment by adonaac** [comment]
Fixed this here https://github.com/adonaac/thranduil/commit/e302f4656ef85ddcae293a9d0e2d0a293da73e32. You can set a default theme by doing `UI.DefaultTheme = YourThemeName`. Note that if you want to use multiple themes then you have to set UI.DefaultTheme to nil and go back to doing it manually.
