### ISSUE TITLE
No z-axis

### ISSUE THREAD

**Issue by Normangorman** [adonaac/thranduil#5]
This is a problem because if you have multiple frames, clicking the top-most frame will trigger click events for all the frames that it obscures. In addition, it is not possible to bring a frame that is obscured to the front of the scene - i.e. the drawing order of frames cannot be changed after they have been created.
I might make more sense to have the UI manager control what gets clicked, rather than have each frame individually check if it is clicked?

![screenshot from 2015-03-08 11 20 59](https://cloud.githubusercontent.com/assets/6610341/6545558/570627ae-c585-11e4-93d6-6963fb901d89.png)

**Comment by adonaac** [comment]
This is up to your application to handle, not this library.

**Comment by Positive07** [comment]
Your lib handles the collision so it is actually a problem with the lib... but do as you please, it's your project anyway

**Comment by adonaac** [comment]
If you don't want a frame to be clicked when it's below another one then check to see if the click triggers multiple frames and choose only one to update. If you want a frame to be drawn on top of another draw it after the previous one. Both are things your application should be able to handle given you can update/draw each element at will.

**Comment by Positive07** [comment]
But you provide an UI element right? Which makes drawing and updating easier right? Then there are two options:

1. Delete that element, leave the update and draw to the user and just to the user

2. Consider this an error with your lib (at least with the UI element)

**Comment by Normangorman** [comment]
It's great that you want to keep the interface flexible to users - this is a good decision. I agree with Positive07 though in that if you're going to offer resizable / draggable frames then you really should offer this feature as well. There is no stacking window manager out there in which click events will penetrate the topmost window. I can't think of anyone not wanting this if they use movable frames in their game.

**Comment by adonaac** [comment]
Anything that has to do with managing multiple UI elements should be on the application side. This is how I built this library and this is how I want it to continue. The "UI manager" part should be nearly non-existent, meaning that caring about what other elements are doing is not something I concern myself with. If you want to build your own UI manager on top of this library it should be easy and that's the kind of stuff this library is built for. Similarly, if you want to build your own non-penetrable Frame UI elements on top of the current ones it should also be easy, just make a class MyFrame, which will contain a normal Frame from this UI library but also additionally have logic for checking other MyFrames of your application.

You can implement the clicking feature on your own by checking if multiple frames have the .selected attribute to true (those are set to true when a frame is interacted with if I remember correctly), setting the ones that are not the top ones to false and then just updating the one that is selected.
