### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by Positive07** [adonaac/thranduil#8]
The problem being that you cant hover buttons, so the button never gets hot and when the mouse is pressed then the collision is false and the click event is not registered.

The solution is checking the collision again when press is called. If you fix issue #7 then that would be pretty easy, just call the collision function again. I guess this could be done through extensions too but  would be a nice feature out of the box. It will be unrivaled since no UI system currently supports touch events

**Comment by adonaac** [comment]
I'm not sure how the collision thing is relevant to touch support, could you explain more? Also, I'm not going to support phones because I don't use phones and I don't have interest nor a phone to test these things with. If you want to you can change it to add this functionality though.

**Comment by Positive07** [comment]
Okey, I guess I can add this through extensions or similar, no problem.

Basically you do this:
```lua
local x, y = love.mouse.getPosition()
if x >= self.x + (self.x_offset or 0) and x <= self.x + (self.x_offset or 0) + (self.area_width or self.w) and 
    y >= self.y + (self.y_offset or 0) and y <= self.y + (self.y_offset or 0) + (self.area_height or self.h) then
    self.hot = true
else self.hot = false end
if self.hot and self.input:pressed('left-click') then
    self.selected = true
elseif not self.hot and self.input:pressed('left-click') then
    self.selected = false
end
```

Since `love.mouse.getPosition()` doesnt return a value on touch devices (the finger is not always down) the hot boolean is always false, and the selected never gets triggered

**Comment by adonaac** [comment]
If you want to support touch just go through all places where I call love.mouse.getPosition() and add the equivalent of love.mouse.getPosition there to get the touch positions I guess? You can just change it directly instead of doing it through extensions (I think doing this through extensions won't work properly either because of updating orders, i.e. hot is always the first thing that gets set to true and other variables are set to true or false based on hot)

**Comment by Positive07** [comment]
I was thinking on calling the press event or something similar, you could also add more events and that would be awesome, something like hold/release would be nice

**Comment by adonaac** [comment]
Each element already has down/released attributes.

**Comment by Positive07** [comment]
Yeah, just wanted something to trigger that, but it would get overriden by the hot evaluation I guess

**Comment by adonaac** [comment]
Like a function call that mimicks hold/released?

**Comment by Positive07** [comment]
Exactly... and the other states maybe... (hold/release would do though)
