### ISSUE TITLE
Changing settings through extensions

### ISSUE THREAD

**Issue by Positive07** [adonaac/thranduil#9]
This is a really weird feature request so please deal with it and don't kill me.

Currently settings are evaluated completely separately from extensions, so extensions cannot touch them or alter them. This means for example that if an extension which doesn't quite support re-sizing or dragging (dragging is less important but re-sizing is a problem) then the user could make an element that crashes passing the re-sizable setting, the idea is passing the settings table to the extension on update so that the extension can change the settings before they are really evaluated.

Just re-sizing is enough but any other setting could be changed, like height width and position

**Comment by adonaac** [comment]
On the update or new function of your extensions you can check if the .resizable attribute is set to true (since you have a reference to the object via self), then if it you handle it however you wanna handle it (either by throwing an error or changing it back to false).

**Comment by Positive07** [comment]
The new function is evaluated before the resizable setting is applied, but I guess update will do... Thanks you!

**Comment by adonaac** [comment]
Thanks for pointing that out, it should be evaluated last and I'll fix that.

**Comment by Positive07** [comment]
Thank you!
